// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EDT {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgNFRFQq8gEKC0VEVDAwMDFFbnVtEg0KCWRlZmF1bHRf",
            "MBAAEgwKB0JhdHRlcnkQ6gcSEQoMQmF0dGVyeV9QYWNrEOsHEhEKDEJBVF9N",
            "T0RVTEVfMBDsBxIRCgxCQVRfTU9EVUxFXzEQ7QcSEQoMQkFUX01PRFVMRV8y",
            "EO4HEhEKDEJBVF9NT0RVTEVfMxDvBxIQCgtFbnZpcm9ubWVudBDwBxIICgNB",
            "SVMQ8QcSEAoLU3lzdGVtX1RpbWUQ8gcSCgoFTU9UT1IQ8wcSDQoISU5WRVJU",
            "RVIQ9AcSDAoHTmV0d29yaxD1BxIQCgtTYXZlQXNCeXRlcxD2ByouCgxNUlNj",
            "aGVtYUVudW0SDQoJZGVmYXVsdF8xEAASDwoKQ19Qb3NpdGlvbhDRD2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EDT.EDT0001Enum), typeof(global::EDT.MRSchemaEnum), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EDT0001Enum {
    [pbr::OriginalName("default_0")] Default0 = 0,
    [pbr::OriginalName("Battery")] Battery = 1002,
    [pbr::OriginalName("Battery_Pack")] BatteryPack = 1003,
    [pbr::OriginalName("BAT_MODULE_0")] BatModule0 = 1004,
    [pbr::OriginalName("BAT_MODULE_1")] BatModule1 = 1005,
    [pbr::OriginalName("BAT_MODULE_2")] BatModule2 = 1006,
    [pbr::OriginalName("BAT_MODULE_3")] BatModule3 = 1007,
    [pbr::OriginalName("Environment")] Environment = 1008,
    [pbr::OriginalName("AIS")] Ais = 1009,
    [pbr::OriginalName("System_Time")] SystemTime = 1010,
    [pbr::OriginalName("MOTOR")] Motor = 1011,
    [pbr::OriginalName("INVERTER")] Inverter = 1012,
    [pbr::OriginalName("Network")] Network = 1013,
    [pbr::OriginalName("SaveAsBytes")] SaveAsBytes = 1014,
  }

  public enum MRSchemaEnum {
    [pbr::OriginalName("default_1")] Default1 = 0,
    [pbr::OriginalName("C_Position")] CPosition = 2001,
  }

  #endregion

}

#endregion Designer generated code
