// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace EDT {

enum EDT0001Enum : int {
  default_0 = 0,
  Battery = 1002,
  Battery_Pack = 1003,
  BAT_MODULE_0 = 1004,
  BAT_MODULE_1 = 1005,
  BAT_MODULE_2 = 1006,
  BAT_MODULE_3 = 1007,
  Environment = 1008,
  AIS = 1009,
  System_Time = 1010,
  MOTOR = 1011,
  INVERTER = 1012,
  Network = 1013,
  SaveAsBytes = 1014,
  EDT0001Enum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EDT0001Enum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EDT0001Enum_IsValid(int value);
constexpr EDT0001Enum EDT0001Enum_MIN = default_0;
constexpr EDT0001Enum EDT0001Enum_MAX = SaveAsBytes;
constexpr int EDT0001Enum_ARRAYSIZE = EDT0001Enum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EDT0001Enum_descriptor();
template<typename T>
inline const std::string& EDT0001Enum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EDT0001Enum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EDT0001Enum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EDT0001Enum_descriptor(), enum_t_value);
}
inline bool EDT0001Enum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EDT0001Enum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EDT0001Enum>(
    EDT0001Enum_descriptor(), name, value);
}
enum MRSchemaEnum : int {
  default_1 = 0,
  C_Position = 2001,
  MRSchemaEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MRSchemaEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MRSchemaEnum_IsValid(int value);
constexpr MRSchemaEnum MRSchemaEnum_MIN = default_1;
constexpr MRSchemaEnum MRSchemaEnum_MAX = C_Position;
constexpr int MRSchemaEnum_ARRAYSIZE = MRSchemaEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MRSchemaEnum_descriptor();
template<typename T>
inline const std::string& MRSchemaEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MRSchemaEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MRSchemaEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MRSchemaEnum_descriptor(), enum_t_value);
}
inline bool MRSchemaEnum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MRSchemaEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MRSchemaEnum>(
    MRSchemaEnum_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace EDT

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::EDT::EDT0001Enum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EDT::EDT0001Enum>() {
  return ::EDT::EDT0001Enum_descriptor();
}
template <> struct is_proto_enum< ::EDT::MRSchemaEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::EDT::MRSchemaEnum>() {
  return ::EDT::MRSchemaEnum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_enum_2eproto
