// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

#include "enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace EDT {
}  // namespace EDT
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_enum_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_enum_2eproto = nullptr;
const uint32_t TableStruct_enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nenum.proto\022\003EDT*\362\001\n\013EDT0001Enum\022\r\n\tdef"
  "ault_0\020\000\022\014\n\007Battery\020\352\007\022\021\n\014Battery_Pack\020\353"
  "\007\022\021\n\014BAT_MODULE_0\020\354\007\022\021\n\014BAT_MODULE_1\020\355\007\022"
  "\021\n\014BAT_MODULE_2\020\356\007\022\021\n\014BAT_MODULE_3\020\357\007\022\020\n"
  "\013Environment\020\360\007\022\010\n\003AIS\020\361\007\022\020\n\013System_Time"
  "\020\362\007\022\n\n\005MOTOR\020\363\007\022\r\n\010INVERTER\020\364\007\022\014\n\007Networ"
  "k\020\365\007\022\020\n\013SaveAsBytes\020\366\007*.\n\014MRSchemaEnum\022\r"
  "\n\tdefault_1\020\000\022\017\n\nC_Position\020\321\017b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_enum_2eproto = {
    false, false, 318, descriptor_table_protodef_enum_2eproto,
    "enum.proto",
    &descriptor_table_enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_enum_2eproto,
    file_level_service_descriptors_enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_enum_2eproto_getter() {
  return &descriptor_table_enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_enum_2eproto(&descriptor_table_enum_2eproto);
namespace EDT {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EDT0001Enum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enum_2eproto);
  return file_level_enum_descriptors_enum_2eproto[0];
}
bool EDT0001Enum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MRSchemaEnum_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enum_2eproto);
  return file_level_enum_descriptors_enum_2eproto[1];
}
bool MRSchemaEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 2001:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace EDT
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
