// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MRSchema.proto

#include "MRSchema.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace MRSchema {
PROTOBUF_CONSTEXPR C_Position::C_Position(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.xpos_)*/0
  , /*decltype(_impl_.ypos_)*/0
  , /*decltype(_impl_.zpos_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_PositionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_PositionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_PositionDefaultTypeInternal() {}
  union {
    C_Position _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_PositionDefaultTypeInternal _C_Position_default_instance_;
PROTOBUF_CONSTEXPR XRCPUPLAN::XRCPUPLAN(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.plandata_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.planrowstride_)*/0
  , /*decltype(_impl_.planpixelstride_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XRCPUPLANDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XRCPUPLANDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XRCPUPLANDefaultTypeInternal() {}
  union {
    XRCPUPLAN _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XRCPUPLANDefaultTypeInternal _XRCPUPLAN_default_instance_;
PROTOBUF_CONSTEXPR XRCPUIMAGE::XRCPUIMAGE(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.plandatas_)*/{}
  , /*decltype(_impl_.id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XRCPUIMAGEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XRCPUIMAGEDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XRCPUIMAGEDefaultTypeInternal() {}
  union {
    XRCPUIMAGE _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XRCPUIMAGEDefaultTypeInternal _XRCPUIMAGE_default_instance_;
}  // namespace MRSchema
static ::_pb::Metadata file_level_metadata_MRSchema_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_MRSchema_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MRSchema_2eproto = nullptr;

const uint32_t TableStruct_MRSchema_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MRSchema::C_Position, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MRSchema::C_Position, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::C_Position, _impl_.xpos_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::C_Position, _impl_.ypos_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::C_Position, _impl_.zpos_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUPLAN, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUPLAN, _impl_.plandata_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUPLAN, _impl_.planrowstride_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUPLAN, _impl_.planpixelstride_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUIMAGE, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUIMAGE, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::MRSchema::XRCPUIMAGE, _impl_.plandatas_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MRSchema::C_Position)},
  { 10, -1, -1, sizeof(::MRSchema::XRCPUPLAN)},
  { 19, -1, -1, sizeof(::MRSchema::XRCPUIMAGE)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::MRSchema::_C_Position_default_instance_._instance,
  &::MRSchema::_XRCPUPLAN_default_instance_._instance,
  &::MRSchema::_XRCPUIMAGE_default_instance_._instance,
};

const char descriptor_table_protodef_MRSchema_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016MRSchema.proto\022\010MRSchema\"B\n\nC_Position"
  "\022\n\n\002ID\030\001 \001(\t\022\014\n\004XPOS\030\002 \001(\002\022\014\n\004YPOS\030\003 \001(\002"
  "\022\014\n\004ZPOS\030\004 \001(\002\"M\n\tXRCPUPLAN\022\020\n\010PLANdata\030"
  "\001 \001(\014\022\025\n\rPLANrowStride\030\002 \001(\005\022\027\n\017PLANpixe"
  "lStride\030\003 \001(\005\"@\n\nXRCPUIMAGE\022\n\n\002ID\030\001 \001(\005\022"
  "&\n\tPLANdatas\030\002 \003(\0132\023.MRSchema.XRCPUPLANb"
  "\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MRSchema_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MRSchema_2eproto = {
    false, false, 247, descriptor_table_protodef_MRSchema_2eproto,
    "MRSchema.proto",
    &descriptor_table_MRSchema_2eproto_once, nullptr, 0, 3,
    schemas, file_default_instances, TableStruct_MRSchema_2eproto::offsets,
    file_level_metadata_MRSchema_2eproto, file_level_enum_descriptors_MRSchema_2eproto,
    file_level_service_descriptors_MRSchema_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MRSchema_2eproto_getter() {
  return &descriptor_table_MRSchema_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MRSchema_2eproto(&descriptor_table_MRSchema_2eproto);
namespace MRSchema {

// ===================================================================

class C_Position::_Internal {
 public:
};

C_Position::C_Position(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MRSchema.C_Position)
}
C_Position::C_Position(const C_Position& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_Position* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.xpos_){}
    , decltype(_impl_.ypos_){}
    , decltype(_impl_.zpos_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.xpos_, &from._impl_.xpos_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.zpos_) -
    reinterpret_cast<char*>(&_impl_.xpos_)) + sizeof(_impl_.zpos_));
  // @@protoc_insertion_point(copy_constructor:MRSchema.C_Position)
}

inline void C_Position::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.xpos_){0}
    , decltype(_impl_.ypos_){0}
    , decltype(_impl_.zpos_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

C_Position::~C_Position() {
  // @@protoc_insertion_point(destructor:MRSchema.C_Position)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_Position::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
}

void C_Position::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_Position::Clear() {
// @@protoc_insertion_point(message_clear_start:MRSchema.C_Position)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  ::memset(&_impl_.xpos_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.zpos_) -
      reinterpret_cast<char*>(&_impl_.xpos_)) + sizeof(_impl_.zpos_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_Position::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "MRSchema.C_Position.ID"));
        } else
          goto handle_unusual;
        continue;
      // float XPOS = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.xpos_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float YPOS = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.ypos_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float ZPOS = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.zpos_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_Position::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MRSchema.C_Position)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ID = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "MRSchema.C_Position.ID");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // float XPOS = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_xpos = this->_internal_xpos();
  uint32_t raw_xpos;
  memcpy(&raw_xpos, &tmp_xpos, sizeof(tmp_xpos));
  if (raw_xpos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_xpos(), target);
  }

  // float YPOS = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ypos = this->_internal_ypos();
  uint32_t raw_ypos;
  memcpy(&raw_ypos, &tmp_ypos, sizeof(tmp_ypos));
  if (raw_ypos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_ypos(), target);
  }

  // float ZPOS = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_zpos = this->_internal_zpos();
  uint32_t raw_zpos;
  memcpy(&raw_zpos, &tmp_zpos, sizeof(tmp_zpos));
  if (raw_zpos != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_zpos(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MRSchema.C_Position)
  return target;
}

size_t C_Position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MRSchema.C_Position)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ID = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // float XPOS = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_xpos = this->_internal_xpos();
  uint32_t raw_xpos;
  memcpy(&raw_xpos, &tmp_xpos, sizeof(tmp_xpos));
  if (raw_xpos != 0) {
    total_size += 1 + 4;
  }

  // float YPOS = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ypos = this->_internal_ypos();
  uint32_t raw_ypos;
  memcpy(&raw_ypos, &tmp_ypos, sizeof(tmp_ypos));
  if (raw_ypos != 0) {
    total_size += 1 + 4;
  }

  // float ZPOS = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_zpos = this->_internal_zpos();
  uint32_t raw_zpos;
  memcpy(&raw_zpos, &tmp_zpos, sizeof(tmp_zpos));
  if (raw_zpos != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_Position::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_Position::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_Position::GetClassData() const { return &_class_data_; }


void C_Position::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_Position*>(&to_msg);
  auto& from = static_cast<const C_Position&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MRSchema.C_Position)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_xpos = from._internal_xpos();
  uint32_t raw_xpos;
  memcpy(&raw_xpos, &tmp_xpos, sizeof(tmp_xpos));
  if (raw_xpos != 0) {
    _this->_internal_set_xpos(from._internal_xpos());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ypos = from._internal_ypos();
  uint32_t raw_ypos;
  memcpy(&raw_ypos, &tmp_ypos, sizeof(tmp_ypos));
  if (raw_ypos != 0) {
    _this->_internal_set_ypos(from._internal_ypos());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_zpos = from._internal_zpos();
  uint32_t raw_zpos;
  memcpy(&raw_zpos, &tmp_zpos, sizeof(tmp_zpos));
  if (raw_zpos != 0) {
    _this->_internal_set_zpos(from._internal_zpos());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_Position::CopyFrom(const C_Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MRSchema.C_Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Position::IsInitialized() const {
  return true;
}

void C_Position::InternalSwap(C_Position* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_Position, _impl_.zpos_)
      + sizeof(C_Position::_impl_.zpos_)
      - PROTOBUF_FIELD_OFFSET(C_Position, _impl_.xpos_)>(
          reinterpret_cast<char*>(&_impl_.xpos_),
          reinterpret_cast<char*>(&other->_impl_.xpos_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C_Position::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MRSchema_2eproto_getter, &descriptor_table_MRSchema_2eproto_once,
      file_level_metadata_MRSchema_2eproto[0]);
}

// ===================================================================

class XRCPUPLAN::_Internal {
 public:
};

XRCPUPLAN::XRCPUPLAN(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MRSchema.XRCPUPLAN)
}
XRCPUPLAN::XRCPUPLAN(const XRCPUPLAN& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XRCPUPLAN* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.plandata_){}
    , decltype(_impl_.planrowstride_){}
    , decltype(_impl_.planpixelstride_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.plandata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.plandata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_plandata().empty()) {
    _this->_impl_.plandata_.Set(from._internal_plandata(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.planrowstride_, &from._impl_.planrowstride_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.planpixelstride_) -
    reinterpret_cast<char*>(&_impl_.planrowstride_)) + sizeof(_impl_.planpixelstride_));
  // @@protoc_insertion_point(copy_constructor:MRSchema.XRCPUPLAN)
}

inline void XRCPUPLAN::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.plandata_){}
    , decltype(_impl_.planrowstride_){0}
    , decltype(_impl_.planpixelstride_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.plandata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.plandata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

XRCPUPLAN::~XRCPUPLAN() {
  // @@protoc_insertion_point(destructor:MRSchema.XRCPUPLAN)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XRCPUPLAN::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.plandata_.Destroy();
}

void XRCPUPLAN::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XRCPUPLAN::Clear() {
// @@protoc_insertion_point(message_clear_start:MRSchema.XRCPUPLAN)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.plandata_.ClearToEmpty();
  ::memset(&_impl_.planrowstride_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.planpixelstride_) -
      reinterpret_cast<char*>(&_impl_.planrowstride_)) + sizeof(_impl_.planpixelstride_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XRCPUPLAN::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes PLANdata = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_plandata();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 PLANrowStride = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.planrowstride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 PLANpixelStride = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.planpixelstride_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XRCPUPLAN::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MRSchema.XRCPUPLAN)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes PLANdata = 1;
  if (!this->_internal_plandata().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_plandata(), target);
  }

  // int32 PLANrowStride = 2;
  if (this->_internal_planrowstride() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_planrowstride(), target);
  }

  // int32 PLANpixelStride = 3;
  if (this->_internal_planpixelstride() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_planpixelstride(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MRSchema.XRCPUPLAN)
  return target;
}

size_t XRCPUPLAN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MRSchema.XRCPUPLAN)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes PLANdata = 1;
  if (!this->_internal_plandata().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_plandata());
  }

  // int32 PLANrowStride = 2;
  if (this->_internal_planrowstride() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_planrowstride());
  }

  // int32 PLANpixelStride = 3;
  if (this->_internal_planpixelstride() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_planpixelstride());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XRCPUPLAN::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XRCPUPLAN::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XRCPUPLAN::GetClassData() const { return &_class_data_; }


void XRCPUPLAN::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XRCPUPLAN*>(&to_msg);
  auto& from = static_cast<const XRCPUPLAN&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MRSchema.XRCPUPLAN)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_plandata().empty()) {
    _this->_internal_set_plandata(from._internal_plandata());
  }
  if (from._internal_planrowstride() != 0) {
    _this->_internal_set_planrowstride(from._internal_planrowstride());
  }
  if (from._internal_planpixelstride() != 0) {
    _this->_internal_set_planpixelstride(from._internal_planpixelstride());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XRCPUPLAN::CopyFrom(const XRCPUPLAN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MRSchema.XRCPUPLAN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XRCPUPLAN::IsInitialized() const {
  return true;
}

void XRCPUPLAN::InternalSwap(XRCPUPLAN* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.plandata_, lhs_arena,
      &other->_impl_.plandata_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XRCPUPLAN, _impl_.planpixelstride_)
      + sizeof(XRCPUPLAN::_impl_.planpixelstride_)
      - PROTOBUF_FIELD_OFFSET(XRCPUPLAN, _impl_.planrowstride_)>(
          reinterpret_cast<char*>(&_impl_.planrowstride_),
          reinterpret_cast<char*>(&other->_impl_.planrowstride_));
}

::PROTOBUF_NAMESPACE_ID::Metadata XRCPUPLAN::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MRSchema_2eproto_getter, &descriptor_table_MRSchema_2eproto_once,
      file_level_metadata_MRSchema_2eproto[1]);
}

// ===================================================================

class XRCPUIMAGE::_Internal {
 public:
};

XRCPUIMAGE::XRCPUIMAGE(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MRSchema.XRCPUIMAGE)
}
XRCPUIMAGE::XRCPUIMAGE(const XRCPUIMAGE& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XRCPUIMAGE* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.plandatas_){from._impl_.plandatas_}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:MRSchema.XRCPUIMAGE)
}

inline void XRCPUIMAGE::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.plandatas_){arena}
    , decltype(_impl_.id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

XRCPUIMAGE::~XRCPUIMAGE() {
  // @@protoc_insertion_point(destructor:MRSchema.XRCPUIMAGE)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XRCPUIMAGE::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.plandatas_.~RepeatedPtrField();
}

void XRCPUIMAGE::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XRCPUIMAGE::Clear() {
// @@protoc_insertion_point(message_clear_start:MRSchema.XRCPUIMAGE)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.plandatas_.Clear();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XRCPUIMAGE::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 ID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .MRSchema.XRCPUPLAN PLANdatas = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_plandatas(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XRCPUIMAGE::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MRSchema.XRCPUIMAGE)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_id(), target);
  }

  // repeated .MRSchema.XRCPUPLAN PLANdatas = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_plandatas_size()); i < n; i++) {
    const auto& repfield = this->_internal_plandatas(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MRSchema.XRCPUIMAGE)
  return target;
}

size_t XRCPUIMAGE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MRSchema.XRCPUIMAGE)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .MRSchema.XRCPUPLAN PLANdatas = 2;
  total_size += 1UL * this->_internal_plandatas_size();
  for (const auto& msg : this->_impl_.plandatas_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 ID = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XRCPUIMAGE::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XRCPUIMAGE::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XRCPUIMAGE::GetClassData() const { return &_class_data_; }


void XRCPUIMAGE::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XRCPUIMAGE*>(&to_msg);
  auto& from = static_cast<const XRCPUIMAGE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MRSchema.XRCPUIMAGE)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.plandatas_.MergeFrom(from._impl_.plandatas_);
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XRCPUIMAGE::CopyFrom(const XRCPUIMAGE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MRSchema.XRCPUIMAGE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XRCPUIMAGE::IsInitialized() const {
  return true;
}

void XRCPUIMAGE::InternalSwap(XRCPUIMAGE* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.plandatas_.InternalSwap(&other->_impl_.plandatas_);
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XRCPUIMAGE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_MRSchema_2eproto_getter, &descriptor_table_MRSchema_2eproto_once,
      file_level_metadata_MRSchema_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace MRSchema
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MRSchema::C_Position*
Arena::CreateMaybeMessage< ::MRSchema::C_Position >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MRSchema::C_Position >(arena);
}
template<> PROTOBUF_NOINLINE ::MRSchema::XRCPUPLAN*
Arena::CreateMaybeMessage< ::MRSchema::XRCPUPLAN >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MRSchema::XRCPUPLAN >(arena);
}
template<> PROTOBUF_NOINLINE ::MRSchema::XRCPUIMAGE*
Arena::CreateMaybeMessage< ::MRSchema::XRCPUIMAGE >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MRSchema::XRCPUIMAGE >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
