// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MRSchema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MRSchema_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MRSchema_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MRSchema_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MRSchema_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MRSchema_2eproto;
namespace MRSchema {
class C_Position;
struct C_PositionDefaultTypeInternal;
extern C_PositionDefaultTypeInternal _C_Position_default_instance_;
}  // namespace MRSchema
PROTOBUF_NAMESPACE_OPEN
template<> ::MRSchema::C_Position* Arena::CreateMaybeMessage<::MRSchema::C_Position>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace MRSchema {

// ===================================================================

class C_Position final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MRSchema.C_Position) */ {
 public:
  inline C_Position() : C_Position(nullptr) {}
  ~C_Position() override;
  explicit PROTOBUF_CONSTEXPR C_Position(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_Position(const C_Position& from);
  C_Position(C_Position&& from) noexcept
    : C_Position() {
    *this = ::std::move(from);
  }

  inline C_Position& operator=(const C_Position& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_Position& operator=(C_Position&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_Position& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_Position* internal_default_instance() {
    return reinterpret_cast<const C_Position*>(
               &_C_Position_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_Position& a, C_Position& b) {
    a.Swap(&b);
  }
  inline void Swap(C_Position* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_Position* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_Position* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_Position>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_Position& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_Position& from) {
    C_Position::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_Position* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MRSchema.C_Position";
  }
  protected:
  explicit C_Position(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIDFieldNumber = 1,
    kXPOSFieldNumber = 2,
    kYPOSFieldNumber = 3,
    kZPOSFieldNumber = 4,
  };
  // string ID = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // float XPOS = 2;
  void clear_xpos();
  float xpos() const;
  void set_xpos(float value);
  private:
  float _internal_xpos() const;
  void _internal_set_xpos(float value);
  public:

  // float YPOS = 3;
  void clear_ypos();
  float ypos() const;
  void set_ypos(float value);
  private:
  float _internal_ypos() const;
  void _internal_set_ypos(float value);
  public:

  // float ZPOS = 4;
  void clear_zpos();
  float zpos() const;
  void set_zpos(float value);
  private:
  float _internal_zpos() const;
  void _internal_set_zpos(float value);
  public:

  // @@protoc_insertion_point(class_scope:MRSchema.C_Position)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    float xpos_;
    float ypos_;
    float zpos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MRSchema_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_Position

// string ID = 1;
inline void C_Position::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& C_Position::id() const {
  // @@protoc_insertion_point(field_get:MRSchema.C_Position.ID)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_Position::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:MRSchema.C_Position.ID)
}
inline std::string* C_Position::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:MRSchema.C_Position.ID)
  return _s;
}
inline const std::string& C_Position::_internal_id() const {
  return _impl_.id_.Get();
}
inline void C_Position::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* C_Position::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* C_Position::release_id() {
  // @@protoc_insertion_point(field_release:MRSchema.C_Position.ID)
  return _impl_.id_.Release();
}
inline void C_Position::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:MRSchema.C_Position.ID)
}

// float XPOS = 2;
inline void C_Position::clear_xpos() {
  _impl_.xpos_ = 0;
}
inline float C_Position::_internal_xpos() const {
  return _impl_.xpos_;
}
inline float C_Position::xpos() const {
  // @@protoc_insertion_point(field_get:MRSchema.C_Position.XPOS)
  return _internal_xpos();
}
inline void C_Position::_internal_set_xpos(float value) {
  
  _impl_.xpos_ = value;
}
inline void C_Position::set_xpos(float value) {
  _internal_set_xpos(value);
  // @@protoc_insertion_point(field_set:MRSchema.C_Position.XPOS)
}

// float YPOS = 3;
inline void C_Position::clear_ypos() {
  _impl_.ypos_ = 0;
}
inline float C_Position::_internal_ypos() const {
  return _impl_.ypos_;
}
inline float C_Position::ypos() const {
  // @@protoc_insertion_point(field_get:MRSchema.C_Position.YPOS)
  return _internal_ypos();
}
inline void C_Position::_internal_set_ypos(float value) {
  
  _impl_.ypos_ = value;
}
inline void C_Position::set_ypos(float value) {
  _internal_set_ypos(value);
  // @@protoc_insertion_point(field_set:MRSchema.C_Position.YPOS)
}

// float ZPOS = 4;
inline void C_Position::clear_zpos() {
  _impl_.zpos_ = 0;
}
inline float C_Position::_internal_zpos() const {
  return _impl_.zpos_;
}
inline float C_Position::zpos() const {
  // @@protoc_insertion_point(field_get:MRSchema.C_Position.ZPOS)
  return _internal_zpos();
}
inline void C_Position::_internal_set_zpos(float value) {
  
  _impl_.zpos_ = value;
}
inline void C_Position::set_zpos(float value) {
  _internal_set_zpos(value);
  // @@protoc_insertion_point(field_set:MRSchema.C_Position.ZPOS)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MRSchema

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MRSchema_2eproto
